# Generated by Django 4.2.18 on 2025-02-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0004_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image_v2',
            field=models.ImageField(blank=True, null=True, upload_to='images_v2/'),
        ),
    ]
